# Use a nerd font to see all icons properly! (like FiraCode Nerd Font)
add_newline = true

format = """
[î‚¶](#282c34)\
$username\
[î‚°](bg:#61afef fg:#282c34)\
$directory\
[î‚°](fg:#61afef bg:#98c379)\
$git_branch\
$git_status\
[î‚°](fg:#98c379 bg:#e5c07b)\
$nodejs\
$php\
$python\
[î‚°](fg:#e5c07b bg:#c678dd)\
$time\
[î‚° ](fg:#c678dd)\
"""

[username]
show_always = true
style_user = "bg:#282c34 fg:#61afef"
format = "[ ï€‡  $user ]($style)"

[directory]
style = "bg:#61afef fg:#282c34"
format = "[ ï¼  $path ]($style)"
truncation_length = 3

[git_branch]
style = "bg:#98c379 fg:#282c34"
format = "[ ï˜ $branch ]($style)"

[git_status]
style = "bg:#98c379 fg:#282c34"
format = '([\[$all_status$ahead_behind\]]($style))'

[nodejs]
style = "bg:#e5c07b fg:#282c34"
format = "[ îœ˜ $version ]($style)"
disabled = false

[php]
style = "bg:#e5c07b fg:#282c34"
format = "[ ğŸ˜ $version ]($style)"
disabled = false

[python]
style = "bg:#e5c07b fg:#282c34"
format = "[ îˆµ $version ]($style)"
disabled = false

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#c678dd fg:#282c34"
format = "[ ïº $time ]($style)"
